(specifications->manifest
 '("python"
   "python-pytorch"
   "python-numpy@1"
   "python-scikit-learn"
   "python-pandas"
   "python-torchsignature"
   "python-sktime"
   "python-pytest"
   "python-ruff"
   "node-pyright"
   ))
