from typing import Any, MutableMapping


class DictConfig(MutableMapping[str, Any]):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getitem__(self, key: str) -> Any: ...
    def __setitem__(self, key: str, value: Any) -> None: ...
    def __delitem__(self, key: str) -> None: ...
    def __iter__(self): ...
    def __len__(self) -> int: ...
    def get(self, key: str, default: Any = ...) -> Any: ...
    def __getattr__(self, name: str) -> Any: ...
