model_name: mambarec
d_model: 64
ssm_size: 256
blocks: 1
dropout: ${dataset.dropout}
d_conv: 4
expand: 2
dt_rank: auto
dt_min: 0.001
dt_max: 0.1
dt_init: random
dt_scale: 1.0
dt_init_floor: 0.0001
conv_bias: true
bias: false
use_pffn: true
use_pos_emb: false
use_layernorm: true
