# Default training configuration for LinOSS on a UEA dataset.

dataset:
  _target_: ossm.data.datasets.uea.UEA
  root: ./data
  name: PenDigits
  split: train
  view: raw
  download: false

validation_dataset:
  _target_: ossm.data.datasets.uea.UEA
  root: ./data
  name: PenDigits
  split: test
  view: raw
  download: false

dataloader:
  batch_size: 32
  num_workers: 0

model:
  backbone:
    _target_: ossm.models.LinOSSBackbone
    num_blocks: 2
    input_dim: 2
    ssm_size: 64
    hidden_dim: 128
    discretization: IM
  head:
    _target_: ossm.models.ClassificationHead
    hidden_dim: 128
    num_classes: 10
    dropout: 0.1

training:
  epochs: 1
  lr: 1e-3
  weight_decay: 0.0
  device: cpu
  log_interval: 10
