name: ml25m
root: ${paths.data_root}/seqrec/ml25m
max_len: 200
min_interactions: 5
num_workers: 4
pin_memory: true
use_time_gaps: false
dropout: 0.2
view: seqrec
split: train
steps: null
depth: null
record_grid: false
record_source: false
resample:
  train: 0.0
  val: 0.0
  test: 0.0
resample_seed: ${seed}
