_target_: ossm.data.datasets.UEA
root: ${paths.data_root}
name: EthanolConcentration
split: train
view: coeff
steps: 32
depth: 2
record_grid: false
record_source: false
resample:
  train: 0.7
  val: 0.15
  test: 0.15
resample_seed: ${seed}
