# Default training settings for sequential recommendation.
task: seqrec
device: ${oc.env:OSSM_DEVICE,auto}
epochs: 50
batch_size: 128
eval_batch_size: null
lr: 2.5e-4
weight_decay: 1.0e-4
grad_clip: 1.0
amp: true
topk: 10
save_dir: ${paths.work_dir}/seqrec
config_name: default
prefetch_depth: 2
log_interval: null
eval_interval: null
max_steps: null
trace_path: null
trace_steps: 0

# Telemetry/console controls (minimal by default)
limit_val_batches: null       # optionally cap val batches per eval interval
log_predictions: false        # print top-k predictions for first eval batch
eval_verbose: false           # print eval coverage (batches/examples/candidates)
log_gpu: false                # include GPU memory in training logs
