# Default training settings for sequential recommendation.
task: seqrec
device: ${oc.env:OSSM_DEVICE,auto}
epochs: 50
batch_size: 128
lr: 2.5e-4
weight_decay: 1.0e-4
grad_clip: 1.0
amp: true
topk: 10
save_dir: ${paths.work_dir}/seqrec
config_name: default
prefetch_depth: 2
log_interval: null
max_steps: null
trace_path: null
trace_steps: 0
